<a href="https://colab.research.google.com/github/Sai-Sudeep-Vadlamudi/Iris-Flower-Classification/blob/main/TASK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly
import plotly.express as px
import cufflinks as cf
import plotly.offline as pyo
import matplotlib.pyplot as plt
from plotly.offline import init_notebook_mode,plot,iplot
# from google.colab import drive
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
# %matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
iris=pd.read_csv('/content/gdrive/MyDrive/oasis DS/Iris.csv')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
print(iris)
iris.drop("Id",axis=1,inplace=True) #here "inplace=true" is used to make changes permanently to variable
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [ ]:
#vizualization
scatter=px.scatter(iris,x="Species",y="PetalWidthCm",size="PetalWidthCm")
scatter.show()
bar=px.bar(iris,x="Species",y="PetalWidthCm")
bar.show()
line=px.line(iris,x="Species",y="PetalWidthCm")
line.show()
scatter_matrix=px.scatter_matrix(iris,color='Species',title='Iris',dimensions=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])
scatter_matrix.show()

In [ ]:
#Data Processing
x=iris.drop("Species",axis=1)
print(x)
y=iris.Species
print(y)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)
x=np.array(x)
print(x)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-

In [ ]:
#Dividing into training and testing data
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)
print(xtest)

[[5.6 2.5 3.9 1.1]
 [5.8 2.8 5.1 2.4]
 [5.7 2.5 5.  2. ]
 [6.1 2.6 5.6 1.4]
 [4.7 3.2 1.6 0.2]
 [5.6 2.9 3.6 1.3]
 [6.9 3.1 5.4 2.1]
 [5.2 4.1 1.5 0.1]
 [6.6 3.  4.4 1.4]
 [6.3 2.3 4.4 1.3]
 [5.5 2.4 3.8 1.1]
 [4.5 2.3 1.3 0.3]
 [5.  3.4 1.6 0.4]
 [5.7 2.8 4.1 1.3]
 [6.3 2.5 4.9 1.5]
 [5.9 3.2 4.8 1.8]
 [5.1 3.5 1.4 0.3]
 [6.  3.  4.8 1.8]
 [6.5 3.  5.2 2. ]
 [7.2 3.6 6.1 2.5]
 [4.8 3.  1.4 0.3]
 [5.  3.5 1.6 0.6]
 [6.3 3.4 5.6 2.4]
 [4.6 3.2 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [6.7 3.  5.2 2.3]
 [5.7 4.4 1.5 0.4]
 [4.6 3.4 1.4 0.3]
 [5.8 2.7 4.1 1. ]
 [4.3 3.  1.1 0.1]
 [7.1 3.  5.9 2.1]
 [4.6 3.6 1.  0.2]
 [5.3 3.7 1.5 0.2]
 [6.1 3.  4.6 1.4]
 [5.5 2.5 4.  1.3]
 [6.7 3.3 5.7 2.5]
 [7.4 2.8 6.1 1.9]
 [4.4 3.2 1.3 0.2]
 [5.  3.4 1.5 0.2]
 [6.4 2.9 4.3 1.3]
 [5.1 3.8 1.5 0.3]
 [7.7 3.  6.1 2.3]
 [4.8 3.1 1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [6.5 3.2 5.1 2. ]]


In [ ]:
#Training the model using Logistic Regression
lr=LogisticRegression()
lr.fit(xtrain,ytrain)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



LogisticRegression()

In [ ]:
#Prediction
prediction=lr.predict(xtest)
prediction = [1 if x >= 0.5 else 0 for x in prediction]
accuracy=accuracy_score(ytest,prediction)*100

In [ ]:
#Accuracy percentage
print("Accuracy for LogisticRegression : ",accuracy)
print(ytest)
print(np.array(prediction))

In [ ]:
#Comparing Predicted data with Testing data
array1=ytest
array2=prediction
fig = px.line(title="Line Graph TestData vs prediction")
fig.add_scatter(x=[i for i in range(len(array1))], y=array1, mode="lines", line=dict(color="blue"), showlegend=True, name="TestData")
fig.add_scatter(x=[i for i in range(len(array2))], y=array2, mode="lines", line=dict(color="red"), showlegend=True, name="Prediction")
fig.show()


# The mismatch between the actual test data and the predicted data on the graph indicates that there is an error in the prediction.
# Here accuracy is very low so we will be using decision tree classifier to improve accuracy



#Using Decision Tree Classifier to increace accuracy
dt=tree.DecisionTreeClassifier()
dt.fit(xtrain,ytrain)



#Prediction
prediction=dt.predict(xtest)
accuracy=accuracy_score(ytest,prediction)*100



#Accuracy percentage
print("Accuracy for DesisionTreeClassifier : ",accuracy)
print(ytest)
print(np.array(prediction))



#Comparing Predicted data with Testing data
array1=ytest
array2=prediction
fig = px.line(title="Line Graph TestData vs prediction")
fig.add_scatter(x=[i for i in range(len(array1))], y=array1, mode="lines", line=dict(color="blue"), showlegend=True, name="TestData")
fig.add_scatter(x=[i for i in range(len(array2))], y=array2, mode="lines", line=dict(color="red"), showlegend=True, name="Prediction")
fig.show()

Accuracy for DesisionTreeClassifier :  97.77777777777777
[1 2 2 2 0 1 2 0 1 1 1 0 0 1 1 1 0 2 2 2 0 0 2 0 0 2 0 0 1 0 2 0 0 1 1 2 2
 0 0 1 0 2 0 1 2]
[1 2 2 2 0 1 2 0 1 1 1 0 0 1 1 2 0 2 2 2 0 0 2 0 0 2 0 0 1 0 2 0 0 1 1 2 2
 0 0 1 0 2 0 1 2]
